const QUIZ_CULTURE = {
  culture_burkina: {
    titre: '🇧🇫 Quiz — Burkina Faso',
    questions: [
      { q: 'Quelle est la capitale du Burkina Faso ?', opts: ['Bobo-Dioulasso', 'Ouagadougou', 'Koudougou', 'Banfora'], rep: 1, expl: 'Reponse correcte : Ouagadougou' },
      { q: 'En quelle annee la Haute-Volta est-elle devenue le Burkina Faso ?', opts: ['1960', '1975', '1984', '1991'], rep: 2, expl: 'Reponse correcte : 1984' },
      { q: 'Que signifie \'Burkina Faso\' ?', opts: ['Terre des ancetres', 'Pays des hommes integres', 'Terre de liberte', 'Pays du soleil'], rep: 1, expl: 'Reponse correcte : Pays des hommes integres' },
      { q: 'Qui a rebaptise la Haute-Volta en Burkina Faso ?', opts: ['Maurice Yameogo', 'Sangoule Lamizana', 'Thomas Sankara', 'Blaise Compaore'], rep: 2, expl: 'Reponse correcte : Thomas Sankara' },
      { q: 'En quelle annee le Burkina Faso a-t-il obtenu son independance ?', opts: ['1958', '1960', '1962', '1965'], rep: 1, expl: 'Reponse correcte : 1960' },
      { q: 'Quelle est la deuxieme ville du Burkina Faso ?', opts: ['Koudougou', 'Banfora', 'Ouahigouya', 'Bobo-Dioulasso'], rep: 3, expl: 'Reponse correcte : Bobo-Dioulasso' },
      { q: 'Quel est le plus long fleuve du Burkina Faso ?', opts: ['Le Nakambe', 'Le Mouhoun', 'Le Niger', 'La Comoe'], rep: 1, expl: 'Reponse correcte : Le Mouhoun' },
      { q: 'Quelle est la monnaie du Burkina Faso ?', opts: ['Le naira', 'Le franc CFA', 'Le cedi', 'Le dalasi'], rep: 1, expl: 'Reponse correcte : Le franc CFA' },
      { q: 'Quel groupe ethnique est le plus nombreux au Burkina Faso ?', opts: ['Les Peuls', 'Les Gourounsi', 'Les Mossi', 'Les Bobo'], rep: 2, expl: 'Reponse correcte : Les Mossi' },
      { q: 'En quelle annee Thomas Sankara a-t-il ete assassine ?', opts: ['1985', '1987', '1989', '1991'], rep: 1, expl: 'Reponse correcte : 1987' },
      { q: 'Quelle est la principale religion pratiquee au Burkina Faso ?', opts: ['Christianisme', 'Islam', 'Animisme', 'Bouddhisme'], rep: 1, expl: 'Reponse correcte : Islam' },
      { q: 'Quel festival culturel majeur se tient a Ouagadougou tous les deux ans ?', opts: ['MASA', 'FESPACO', 'SIAO', 'Panafest'], rep: 1, expl: 'Reponse correcte : FESPACO' },
      { q: 'Le SIAO est un salon dedie a quoi ?', opts: ['L\'agriculture', 'L\'artisanat africain', 'Le cinema', 'La musique'], rep: 1, expl: 'Reponse correcte : L\'artisanat africain' },
      { q: 'Quelle est la langue officielle du Burkina Faso ?', opts: ['Le moore', 'Le dioula', 'Le mooré', 'Le fulfulde'], rep: 2, expl: 'Reponse correcte : Le mooré' },
      { q: 'Combien de regions compte le Burkina Faso ?', opts: ['11', '13', '15', '17'], rep: 1, expl: 'Reponse correcte : 13' },
      { q: 'Quel est le premier president de la Haute-Volta ?', opts: ['Sangoule Lamizana', 'Maurice Yameogo', 'Thomas Sankara', 'Gerard Kango Ouedraogo'], rep: 1, expl: 'Reponse correcte : Maurice Yameogo' },
      { q: 'La ville de Bobo-Dioulasso est connue pour quelle attraction ?', opts: ['La Grande Mosquee', 'Le Palais Royal', 'Les chutes d\'eau de Banfora', 'La Mosquee de Dioulassoba'], rep: 3, expl: 'Reponse correcte : La Mosquee de Dioulassoba' },
      { q: 'Quel animal figure sur les armoiries du Burkina Faso ?', opts: ['Le lion', 'L\'etalon', 'L\'elephant', 'Le buffle'], rep: 1, expl: 'Reponse correcte : L\'etalon' },
      { q: 'Quelle est la principale culture d\'exportation du Burkina Faso ?', opts: ['Le cacao', 'Le coton', 'Le cafe', 'L\'arachide'], rep: 1, expl: 'Reponse correcte : Le coton' },
      { q: 'Quelle est la date de la fete nationale du Burkina Faso ?', opts: ['5 aout', '11 decembre', '4 aout', '15 aout'], rep: 1, expl: 'Reponse correcte : 11 decembre' },
      { q: 'Qu\'est-ce que le to (tô) ?', opts: ['Un riz cuit', 'Une pate epaisse a base de mil ou de sorgho', 'Un legume', 'Un ragout'], rep: 1, expl: 'Reponse correcte : Une pate epaisse a base de mil ou de sorgho' },
      { q: 'Qu\'est-ce que le dolo au Burkina Faso ?', opts: ['Un plat', 'Une biere traditionnelle a base de sorgho', 'Un condiment', 'Un fruit'], rep: 1, expl: 'Reponse correcte : Une biere traditionnelle a base de sorgho' },
      { q: 'Qui etait Joseph Ki-Zerbo ?', opts: ['President du Burkina', 'Historien burkinabe de renommee mondiale', 'General de l\'armee', 'Premier ministre'], rep: 1, expl: 'Reponse correcte : Historien burkinabe de renommee mondiale' },
      { q: 'Qu\'est-ce que le Mogho Naaba ?', opts: ['Chef politique burkinabe', 'Roi traditionnel supreme des Mossi', 'Chef religieux', 'Nom d\'un festival'], rep: 1, expl: 'Reponse correcte : Roi traditionnel supreme des Mossi' },
      { q: 'Qu\'est-ce que le balafon ?', opts: ['Un instrument a cordes', 'Un xylophone traditionnel africain', 'Un tambour', 'Une flute'], rep: 1, expl: 'Reponse correcte : Un xylophone traditionnel africain' },
    ]
  },
  culture_afrique: {
    titre: '🌍 Quiz — Histoire & Géo Afrique',
    questions: [
      { q: 'Quel pays africain n\'a jamais ete colonise ?', opts: ['Le Ghana', 'Le Nigeria', 'L\'Ethiopie', 'Le Kenya'], rep: 2, expl: 'Reponse correcte : L\'Ethiopie' },
      { q: 'La conference de Berlin (1884-1885) a decide quoi ?', opts: ['La fin de l\'esclavage', 'Le partage de l\'Afrique', 'La creation de l\'ONU', 'L\'independance du Congo'], rep: 1, expl: 'Reponse correcte : Le partage de l\'Afrique' },
      { q: 'Quel est le pays le plus peuple d\'Afrique ?', opts: ['L\'Ethiopie', 'Le Congo', 'L\'Egypte', 'Le Nigeria'], rep: 3, expl: 'Reponse correcte : Le Nigeria' },
      { q: 'Ou se trouve le mont Kilimandjaro ?', opts: ['Kenya', 'Ethiopie', 'Tanzanie', 'Ouganda'], rep: 2, expl: 'Reponse correcte : Tanzanie' },
      { q: 'Quel fleuve est le plus long du monde ?', opts: ['L\'Amazone', 'Le Congo', 'Le Nil', 'Le Niger'], rep: 2, expl: 'Reponse correcte : Le Nil' },
      { q: 'Nelson Mandela a ete president de quel pays ?', opts: ['Zimbabwe', 'Namibie', 'Afrique du Sud', 'Mozambique'], rep: 2, expl: 'Reponse correcte : Afrique du Sud' },
      { q: 'Qui etait Patrice Lumumba ?', opts: ['President du Senegal', 'Premier ministre du Congo', 'Roi du Maroc', 'General camerounais'], rep: 1, expl: 'Reponse correcte : Premier ministre du Congo' },
      { q: 'Qui etait Soundjata Keita ?', opts: ['Roi du Bornou', 'Fondateur de l\'Empire du Mali', 'Chef de l\'empire du Ghana', 'Roi du Kanem'], rep: 1, expl: 'Reponse correcte : Fondateur de l\'Empire du Mali' },
      { q: 'Qui etait Mansa Moussa ?', opts: ['Roi du Songhai', 'Roi du Mali celebre pour son pelerinage a La Mecque', 'Pharaon egyptien', 'Roi du Bornou'], rep: 1, expl: 'Reponse correcte : Roi du Mali celebre pour son pelerinage a La Mecque' },
      { q: 'Quelle est la capitale du Senegal ?', opts: ['Abidjan', 'Dakar', 'Conakry', 'Bamako'], rep: 1, expl: 'Reponse correcte : Dakar' },
      { q: 'Quel est le plus grand pays d\'Afrique en superficie ?', opts: ['Le Soudan', 'L\'Algerie', 'La RDC', 'La Libye'], rep: 1, expl: 'Reponse correcte : L\'Algerie' },
      { q: 'Quelle est la capitale du Ghana ?', opts: ['Lagos', 'Accra', 'Lome', 'Cotonou'], rep: 1, expl: 'Reponse correcte : Accra' },
      { q: 'Qui etait Kwame Nkrumah ?', opts: ['Premier president de la Cote d\'Ivoire', 'Premier president du Ghana', 'President du Nigeria', 'Premier ministre du Senegal'], rep: 1, expl: 'Reponse correcte : Premier president du Ghana' },
      { q: 'Quelle est la capitale du Mali ?', opts: ['Niamey', 'Bamako', 'Ouagadougou', 'N\'Djamena'], rep: 1, expl: 'Reponse correcte : Bamako' },
      { q: 'Qu\'est-ce que le Sahel ?', opts: ['Un desert de sable', 'Une zone de transition entre Sahara et savane', 'Une foret tropicale', 'Une zone cotiere'], rep: 1, expl: 'Reponse correcte : Une zone de transition entre Sahara et savane' },
      { q: 'Qui etait Cheikh Anta Diop ?', opts: ['President senegalais', 'Historien et scientifique senegalais', 'General malien', 'Poete burkinabe'], rep: 1, expl: 'Reponse correcte : Historien et scientifique senegalais' },
      { q: 'Quand a ete fondee l\'OUA ?', opts: ['1955', '1960', '1963', '1965'], rep: 2, expl: 'Reponse correcte : 1963' },
      { q: 'L\'OUA a ete remplacee par quelle organisation en 2002 ?', opts: ['CEDEAO', 'SADC', 'Union Africaine', 'NEPAD'], rep: 2, expl: 'Reponse correcte : Union Africaine' },
      { q: 'Qui etait Felix Houphouet-Boigny ?', opts: ['Premier president du Senegal', 'Premier president de la Cote d\'Ivoire', 'President du Ghana', 'President du Cameroun'], rep: 1, expl: 'Reponse correcte : Premier president de la Cote d\'Ivoire' },
      { q: 'Qu\'est-ce que la traite negriere ?', opts: ['Le commerce de l\'ivoire', 'Le commerce d\'etres humains reduits en esclavage', 'La migration volontaire', 'Le commerce d\'epices'], rep: 1, expl: 'Reponse correcte : Le commerce d\'etres humains reduits en esclavage' },
      { q: 'Quelle est la capitale de l\'Ethiopie ?', opts: ['Nairobi', 'Addis-Abeba', 'Kampala', 'Khartoum'], rep: 1, expl: 'Reponse correcte : Addis-Abeba' },
      { q: 'Quel est le plus grand lac d\'Afrique ?', opts: ['Lac Tanganyika', 'Lac Malawi', 'Lac Victoria', 'Lac Tchad'], rep: 2, expl: 'Reponse correcte : Lac Victoria' },
      { q: 'Qu\'est-ce que le panafricanisme ?', opts: ['Un mouvement d\'unite du peuple africain', 'Un parti politique', 'Un style musical', 'Une religion africaine'], rep: 0, expl: 'Reponse correcte : Un mouvement d\'unite du peuple africain' },
      { q: 'Quel est le pays le plus petit d\'Afrique ?', opts: ['Djibouti', 'Les Seychelles', 'Sao Tome-et-Principe', 'Les Comores'], rep: 1, expl: 'Reponse correcte : Les Seychelles' },
      { q: 'Ou se trouve l\'ile de Madagascar ?', opts: ['Atlantique', 'Pacifique', 'Ocean Indien', 'Mediterranee'], rep: 2, expl: 'Reponse correcte : Ocean Indien' },
    ]
  },
  culture_sciences: {
    titre: '🔬 Quiz — Sciences & Découvertes',
    questions: [
      { q: 'Qui a decouvert la penicilline ?', opts: ['Louis Pasteur', 'Marie Curie', 'Alexander Fleming', 'Albert Einstein'], rep: 2, expl: 'Reponse correcte : Alexander Fleming' },
      { q: 'Quelle est la planete la plus proche du Soleil ?', opts: ['Venus', 'Terre', 'Mars', 'Mercure'], rep: 3, expl: 'Reponse correcte : Mercure' },
      { q: 'A quelle vitesse la lumiere se deplace-t-elle dans le vide ?', opts: ['150 000 km/s', '300 000 km/s', '450 000 km/s', '600 000 km/s'], rep: 1, expl: 'Reponse correcte : 300 000 km/s' },
      { q: 'Quel gaz les plantes produisent-elles lors de la photosynthese ?', opts: ['CO2', 'N2', 'O2', 'H2'], rep: 2, expl: 'Reponse correcte : O2' },
      { q: 'Combien d\'os compte le corps humain adulte ?', opts: ['106', '206', '306', '406'], rep: 1, expl: 'Reponse correcte : 206' },
      { q: 'Qui a formule la theorie de la relativite ?', opts: ['Newton', 'Einstein', 'Bohr', 'Planck'], rep: 1, expl: 'Reponse correcte : Einstein' },
      { q: 'Quel est le symbole chimique de l\'or ?', opts: ['Or', 'Go', 'Au', 'Ag'], rep: 2, expl: 'Reponse correcte : Au' },
      { q: 'Combien de chromosomes possede une cellule humaine ?', opts: ['23', '36', '46', '48'], rep: 2, expl: 'Reponse correcte : 46' },
      { q: 'Quel est le point d\'ebullition de l\'eau a pression normale ?', opts: ['90C', '95C', '100C', '105C'], rep: 2, expl: 'Reponse correcte : 100C' },
      { q: 'Quel scientifique a decouvert la loi de la gravitation universelle ?', opts: ['Galilee', 'Copernic', 'Newton', 'Kepler'], rep: 2, expl: 'Reponse correcte : Newton' },
      { q: 'Quel est le plus grand organe du corps humain ?', opts: ['Le foie', 'Le poumon', 'La peau', 'L\'intestin'], rep: 2, expl: 'Reponse correcte : La peau' },
      { q: 'Qui a invente l\'ampoule electrique ?', opts: ['Tesla', 'Edison', 'Volta', 'Franklin'], rep: 1, expl: 'Reponse correcte : Edison' },
      { q: 'Quelle est la formule chimique de l\'eau ?', opts: ['HO', 'H2O', 'H2O2', 'OH'], rep: 1, expl: 'Reponse correcte : H2O' },
      { q: 'Combien de dents un adulte possede-t-il normalement ?', opts: ['28', '30', '32', '34'], rep: 2, expl: 'Reponse correcte : 32' },
      { q: 'Qui a decouvert l\'Amerique en 1492 ?', opts: ['Vasco de Gama', 'Christophe Colomb', 'Magellan', 'Amerigo Vespucci'], rep: 1, expl: 'Reponse correcte : Christophe Colomb' },
      { q: 'Quelle est la vitesse du son dans l\'air ?', opts: ['143 m/s', '243 m/s', '343 m/s', '443 m/s'], rep: 2, expl: 'Reponse correcte : 343 m/s' },
      { q: 'Quel est l\'organe qui filtre le sang dans le corps humain ?', opts: ['Le foie', 'Le poumon', 'Le rein', 'La rate'], rep: 2, expl: 'Reponse correcte : Le rein' },
      { q: 'Marie Curie a decouvert quels elements radioactifs ?', opts: ['Uranium et plutonium', 'Radium et polonium', 'Thorium et radon', 'Cesium et strontium'], rep: 1, expl: 'Reponse correcte : Radium et polonium' },
      { q: 'Quel est le plus grand mammifere terrestre ?', opts: ['Le rhinoceros', 'L\'hippopotame', 'L\'elephant d\'Afrique', 'La girafe'], rep: 2, expl: 'Reponse correcte : L\'elephant d\'Afrique' },
      { q: 'Qui est considere comme le pere de la biologie moderne ?', opts: ['Darwin', 'Mendel', 'Pasteur', 'Aristote'], rep: 3, expl: 'Reponse correcte : Aristote' },
      { q: 'Quel est l\'animal le plus rapide du monde ?', opts: ['Le guepard', 'L\'aigle', 'Le faucon pelerin', 'Le lion'], rep: 2, expl: 'Reponse correcte : Le faucon pelerin' },
      { q: 'Qui a invente le telephone ?', opts: ['Edison', 'Marconi', 'Bell', 'Morse'], rep: 2, expl: 'Reponse correcte : Bell' },
      { q: 'Quelle est la planete la plus grande du systeme solaire ?', opts: ['Saturne', 'Jupiter', 'Uranus', 'Neptune'], rep: 1, expl: 'Reponse correcte : Jupiter' },
      { q: 'Combien de planetes compte notre systeme solaire ?', opts: ['7', '8', '9', '10'], rep: 1, expl: 'Reponse correcte : 8' },
      { q: 'Quel est le plus grand ocean du monde ?', opts: ['Atlantique', 'Indien', 'Arctique', 'Pacifique'], rep: 3, expl: 'Reponse correcte : Pacifique' },
    ]
  },
  culture_svt_pc: {
    titre: '⚗️ Quiz — SVT & Physique-Chimie',
    questions: [
      { q: 'Quel gaz les plantes absorbent-elles lors de la photosynthese ?', opts: ['O2', 'CO2', 'N2', 'H2O'], rep: 1, expl: 'Reponse correcte : CO2' },
      { q: 'Dans quelle structure se deroule la photosynthese ?', opts: ['Mitochondrie', 'Noyau', 'Chloroplaste', 'Ribosome'], rep: 2, expl: 'Reponse correcte : Chloroplaste' },
      { q: 'Quel organe produit la bile ?', opts: ['L\'estomac', 'Le foie', 'Le pancreas', 'Le rein'], rep: 1, expl: 'Reponse correcte : Le foie' },
      { q: 'Combien de paires de chromosomes possede la cellule humaine ?', opts: ['23 paires', '22 paires', '46 paires', '24 paires'], rep: 0, expl: 'Reponse correcte : 23 paires' },
      { q: 'Qu\'est-ce que la selection naturelle selon Darwin ?', opts: ['Les individus les plus forts survivent', 'Les individus les mieux adaptes survivent', 'Les mutations aleatoires', 'L\'evolution controlee'], rep: 1, expl: 'Reponse correcte : Les individus les mieux adaptes survivent' },
      { q: 'Qu\'est-ce qu\'un gene ?', opts: ['Un type de proteine', 'Un segment d\'ADN codant pour une proteine', 'Un acide amine', 'Un chromosome entier'], rep: 1, expl: 'Reponse correcte : Un segment d\'ADN codant pour une proteine' },
      { q: 'Quelle hormone regule la glycemie ?', opts: ['Adrenaline', 'Cortisol', 'Insuline', 'Thyroxine'], rep: 2, expl: 'Reponse correcte : Insuline' },
      { q: 'Selon la loi d\'Ohm, si U = 12 V et R = 4 Ohm, quelle est l\'intensite I ?', opts: ['3 A', '8 A', '48 A', '16 A'], rep: 0, expl: 'Reponse correcte : 3 A' },
      { q: 'Une solution de pH = 3 est :', opts: ['Neutre', 'Basique', 'Acide', 'Saline'], rep: 2, expl: 'Reponse correcte : Acide' },
      { q: 'Quelle est l\'unite de mesure de la force en physique ?', opts: ['Joule (J)', 'Watt (W)', 'Newton (N)', 'Pascal (Pa)'], rep: 2, expl: 'Reponse correcte : Newton (N)' },
      { q: 'Quel est le symbole chimique du sodium ?', opts: ['So', 'Sd', 'Na', 'Sm'], rep: 2, expl: 'Reponse correcte : Na' },
      { q: 'Qu\'est-ce qu\'un acide selon Bronsted ?', opts: ['Un donneur de protons', 'Un accepteur de protons', 'Un donneur d\'electrons', 'Un accepteur d\'oxygene'], rep: 0, expl: 'Reponse correcte : Un donneur de protons' },
      { q: 'Qu\'est-ce que la masse molaire ?', opts: ['La masse d\'une molecule en grammes', 'La masse d\'une mole de substance en g/mol', 'La densite d\'un gaz', 'Le volume molaire'], rep: 1, expl: 'Reponse correcte : La masse d\'une mole de substance en g/mol' },
      { q: 'Quelle est la charge d\'un proton ?', opts: ['Negative', 'Nulle', 'Positive', 'Variable'], rep: 2, expl: 'Reponse correcte : Positive' },
      { q: 'Qu\'est-ce qu\'un isotope ?', opts: ['Atome avec un nombre different d\'electrons', 'Atome avec un nombre different de neutrons', 'Atome avec un nombre different de protons', 'Molecule differente'], rep: 1, expl: 'Reponse correcte : Atome avec un nombre different de neutrons' },
      { q: 'Qu\'est-ce que le paludisme et son vecteur ?', opts: ['Maladie virale transmise par la mouche', 'Maladie parasitaire transmise par l\'anophele femelle', 'Maladie bacterienne transmise par l\'eau', 'Maladie genetique'], rep: 1, expl: 'Reponse correcte : Maladie parasitaire transmise par l\'anophele femelle' },
      { q: 'Qu\'est-ce que la drepanocytose ?', opts: ['Une maladie infectieuse', 'Une maladie genetique des globules rouges', 'Un cancer du sang', 'Une carence en vitamines'], rep: 1, expl: 'Reponse correcte : Une maladie genetique des globules rouges' },
      { q: 'Quel est le role des globules rouges ?', opts: ['Defendre contre les infections', 'Transporter l\'oxygene', 'Coaguler le sang', 'Produire des anticorps'], rep: 1, expl: 'Reponse correcte : Transporter l\'oxygene' },
      { q: 'Qu\'est-ce que la respiration cellulaire ?', opts: ['Le mecanisme de la toux', 'La production d\'ATP a partir du glucose', 'L\'echange de gaz dans les poumons', 'La circulation sanguine'], rep: 1, expl: 'Reponse correcte : La production d\'ATP a partir du glucose' },
      { q: 'Qu\'est-ce qu\'un ecosysteme ?', opts: ['Un ensemble d\'especes seulement', 'L\'ensemble des etres vivants et leur milieu', 'Un type de sol', 'Une chaine alimentaire'], rep: 1, expl: 'Reponse correcte : L\'ensemble des etres vivants et leur milieu' },
      { q: 'Quelle est la formule chimique du dioxyde de carbone ?', opts: ['CO', 'CO2', 'C2O', 'HCO3'], rep: 1, expl: 'Reponse correcte : CO2' },
      { q: 'Qu\'est-ce que l\'OMS ?', opts: ['Organisation Mondiale de la Sante', 'Organisation Medicale du Sahel', 'Office Mondial du Sport', 'Organisation des Medecins du Sahel'], rep: 0, expl: 'Reponse correcte : Organisation Mondiale de la Sante' },
      { q: 'Qu\'est-ce que le SIDA ?', opts: ['Syndrome d\'ImmunoDeficience Acquise', 'Systeme d\'Immunite Durable Africaine', 'Syndrome Inflammatoire Durable Aigu', 'Systeme Infectieux Diffus Aigu'], rep: 0, expl: 'Reponse correcte : Syndrome d\'ImmunoDeficience Acquise' },
      { q: 'Quel virus cause le SIDA ?', opts: ['VPH', 'VIH', 'VEB', 'VRS'], rep: 1, expl: 'Reponse correcte : VIH' },
      { q: 'Qu\'est-ce que la malnutrition ?', opts: ['Manger trop', 'Un apport alimentaire insuffisant ou desequilibre', 'Manger sans sel', 'Une allergie alimentaire'], rep: 1, expl: 'Reponse correcte : Un apport alimentaire insuffisant ou desequilibre' },
    ]
  },
  culture_arts: {
    titre: '🎨 Quiz — Arts, Littérature & Philosophie',
    questions: [
      { q: 'Qui a ecrit \'Les Miserables\' ?', opts: ['Balzac', 'Zola', 'Victor Hugo', 'Flaubert'], rep: 2, expl: 'Reponse correcte : Victor Hugo' },
      { q: 'Qui a peint la Joconde ?', opts: ['Michel-Ange', 'Raphael', 'Leonard de Vinci', 'Botticelli'], rep: 2, expl: 'Reponse correcte : Leonard de Vinci' },
      { q: 'Qui a ecrit \'L\'Enfant noir\' ?', opts: ['Aime Cesaire', 'Camara Laye', 'Cheikh H. Kane', 'Sembene Ousmane'], rep: 1, expl: 'Reponse correcte : Camara Laye' },
      { q: 'Leopold Sedar Senghor etait a la fois poete et ?', opts: ['General', 'Roi', 'President du Senegal', 'Ministre francais'], rep: 2, expl: 'Reponse correcte : President du Senegal' },
      { q: 'Qu\'est-ce que la negritude ?', opts: ['Un mouvement musical', 'Un mouvement litteraire et culturel africain', 'Une danse traditionnelle', 'Un courant politique'], rep: 1, expl: 'Reponse correcte : Un mouvement litteraire et culturel africain' },
      { q: 'Quel auteur africain a remporte le prix Nobel de litterature en 1986 ?', opts: ['Ngugi wa Thiong\'o', 'Chinua Achebe', 'Wole Soyinka', 'Ben Okri'], rep: 2, expl: 'Reponse correcte : Wole Soyinka' },
      { q: 'Qu\'est-ce que le griot en Afrique de l\'Ouest ?', opts: ['Un guerrier', 'Un gardien de la memoire et musicien', 'Un chef religieux', 'Un forgeron'], rep: 1, expl: 'Reponse correcte : Un gardien de la memoire et musicien' },
      { q: 'Qui a ecrit \'Hamlet\' ?', opts: ['Moliere', 'Shakespeare', 'Racine', 'Corneille'], rep: 1, expl: 'Reponse correcte : Shakespeare' },
      { q: 'Qui a ecrit \'Le Petit Prince\' ?', opts: ['Jules Verne', 'Antoine de Saint-Exupery', 'Albert Camus', 'Jean-Paul Sartre'], rep: 1, expl: 'Reponse correcte : Antoine de Saint-Exupery' },
      { q: 'Qu\'est-ce qu\'une metaphore ?', opts: ['Comparaison avec \'comme\'', 'Exageration', 'Comparaison sans outil comparatif', 'Repetition'], rep: 2, expl: 'Reponse correcte : Comparaison sans outil comparatif' },
      { q: 'Qui a ecrit \'Une si longue lettre\' ?', opts: ['Ken Bugul', 'Mariama Ba', 'Aminata Sow Fall', 'Calixthe Beyala'], rep: 1, expl: 'Reponse correcte : Mariama Ba' },
      { q: 'Qui a ecrit \'Les Soleils des Independances\' ?', opts: ['Kofi Awoonor', 'Ahmadou Kourouma', 'Birago Diop', 'Ferdinand Oyono'], rep: 1, expl: 'Reponse correcte : Ahmadou Kourouma' },
      { q: 'Qui a dit \'Je pense, donc je suis\' ?', opts: ['Kant', 'Descartes', 'Voltaire', 'Rousseau'], rep: 1, expl: 'Reponse correcte : Descartes' },
      { q: 'Qui est considere comme le pere de la philosophie occidentale ?', opts: ['Platon', 'Aristote', 'Socrate', 'Pythagore'], rep: 2, expl: 'Reponse correcte : Socrate' },
      { q: 'Qui a ecrit \'La Republique\' ?', opts: ['Aristote', 'Socrate', 'Platon', 'Epicure'], rep: 2, expl: 'Reponse correcte : Platon' },
      { q: 'Qui est le fondateur de l\'existentialisme moderne ?', opts: ['Camus', 'Sartre', 'Heidegger', 'Nietzsche'], rep: 1, expl: 'Reponse correcte : Sartre' },
      { q: 'Qui a dit \'L\'homme est un animal politique\' ?', opts: ['Platon', 'Socrate', 'Aristote', 'Epicure'], rep: 2, expl: 'Reponse correcte : Aristote' },
      { q: 'Qui a ecrit \'Le Contrat social\' ?', opts: ['Voltaire', 'Montesquieu', 'Rousseau', 'Diderot'], rep: 2, expl: 'Reponse correcte : Rousseau' },
      { q: 'Qui a dit \'Connais-toi toi-meme\' ?', opts: ['Platon', 'Aristote', 'Socrate', 'Diogene'], rep: 2, expl: 'Reponse correcte : Socrate' },
      { q: 'Qui est Albert Camus ?', opts: ['Philosophe allemand', 'Ecrivain et philosophe algerien-francais, Prix Nobel 1957', 'Dramaturge americain', 'Romancier russe'], rep: 1, expl: 'Reponse correcte : Ecrivain et philosophe algerien-francais, Prix Nobel 1957' },
      { q: 'Qui est Frantz Fanon ?', opts: ['Philosophe francais', 'Psychiatre et theoricien martiniquais de la decolonisation', 'Ecrivain senegalais', 'Politicien algerien'], rep: 1, expl: 'Reponse correcte : Psychiatre et theoricien martiniquais de la decolonisation' },
      { q: 'Qui est Moliere ?', opts: ['Tragedien francais', 'Dramaturge comique francais du 17e siecle', 'Philosophe des Lumieres', 'Poete romantique'], rep: 1, expl: 'Reponse correcte : Dramaturge comique francais du 17e siecle' },
      { q: 'Qui a sculpte \'Le Penseur\' ?', opts: ['Michel-Ange', 'Rodin', 'Brancusi', 'Giacometti'], rep: 1, expl: 'Reponse correcte : Rodin' },
      { q: 'Qui a compose la 9e symphonie ?', opts: ['Mozart', 'Bach', 'Beethoven', 'Chopin'], rep: 2, expl: 'Reponse correcte : Beethoven' },
      { q: 'Quel peintre est connu pour ses tournesols ?', opts: ['Picasso', 'Monet', 'Van Gogh', 'Renoir'], rep: 2, expl: 'Reponse correcte : Van Gogh' },
      { q: 'Qui a ecrit \'L\'Etranger\' ?', opts: ['Sartre', 'Camus', 'Malraux', 'Gide'], rep: 1, expl: 'Reponse correcte : Camus' },
      { q: 'Qu\'est-ce que le cubisme ?', opts: ['Un style de danse', 'Un mouvement pictural geometrique', 'Une architecture moderne', 'Un courant musical'], rep: 1, expl: 'Reponse correcte : Un mouvement pictural geometrique' },
      { q: 'Qui est l\'auteur de \'L\'aventure ambigue\' ?', opts: ['Mongo Beti', 'Cheikh H. Kane', 'Birago Diop', 'Bernard Dadie'], rep: 1, expl: 'Reponse correcte : Cheikh H. Kane' },
      { q: 'Qu\'est-ce qu\'une epopee ?', opts: ['Un poeme lyrique court', 'Un long recit d\'exploits heroiques', 'Une piece de theatre comique', 'Un roman realiste'], rep: 1, expl: 'Reponse correcte : Un long recit d\'exploits heroiques' },
      { q: 'Qui est l\'auteur de \'Soundjata ou l\'epopee mandingue\' ?', opts: ['Ahmadou Kourouma', 'Djibril Tamsir Niane', 'Leopold Sedar Senghor', 'Mongo Beti'], rep: 1, expl: 'Reponse correcte : Djibril Tamsir Niane' },
    ]
  },
  culture_monde: {
    titre: '🌐 Quiz — Monde Contemporain',
    questions: [
      { q: 'Quand l\'ONU a-t-elle ete fondee ?', opts: ['1919', '1939', '1945', '1948'], rep: 2, expl: 'Reponse correcte : 1945' },
      { q: 'Combien de pays membres compte l\'ONU ?', opts: ['154', '173', '193', '213'], rep: 2, expl: 'Reponse correcte : 193' },
      { q: 'Quelle est la monnaie de l\'Union Europeenne ?', opts: ['Le dollar', 'La livre sterling', 'L\'euro', 'Le franc'], rep: 2, expl: 'Reponse correcte : L\'euro' },
      { q: 'Qu\'est-ce que la mondialisation ?', opts: ['L\'uniformisation des cultures', 'L\'interdependance croissante des economies et societes', 'La disparition des frontieres', 'Le developpement du commerce local'], rep: 1, expl: 'Reponse correcte : L\'interdependance croissante des economies et societes' },
      { q: 'Qu\'est-ce que le PIB ?', opts: ['Produit Interieur Brut', 'Programme International de Bien-etre', 'Politique Internationale de Banque', 'Plan d\'Investissement Brut'], rep: 0, expl: 'Reponse correcte : Produit Interieur Brut' },
      { q: 'Qu\'est-ce que le rechauffement climatique ?', opts: ['L\'augmentation naturelle des temperatures', 'L\'augmentation des temperatures due aux emissions humaines', 'Le refroidissement de l\'Arctique', 'Les eruptions volcaniques'], rep: 1, expl: 'Reponse correcte : L\'augmentation des temperatures due aux emissions humaines' },
      { q: 'Quel accord international vise a limiter le rechauffement climatique ?', opts: ['Accord de Kyoto', 'Accord de Paris', 'Protocole de Montreal', 'Convention de Geneve'], rep: 1, expl: 'Reponse correcte : Accord de Paris' },
      { q: 'Qu\'est-ce que la democratie representative ?', opts: ['Voter directement toutes les lois', 'Elire des representants qui gouvernent', 'Le gouvernement d\'un seul parti', 'Le gouvernement des experts'], rep: 1, expl: 'Reponse correcte : Elire des representants qui gouvernent' },
      { q: 'Qu\'est-ce que le developpement durable ?', opts: ['La croissance economique illimitee', 'Le developpement qui repond aux besoins presents sans compromettre l\'avenir', 'L\'industrialisation rapide', 'L\'exploitation maximale des ressources'], rep: 1, expl: 'Reponse correcte : Le developpement qui repond aux besoins presents sans compromettre l\'avenir' },
      { q: 'Qu\'est-ce que les droits de l\'homme ?', opts: ['Les droits accordes par le gouvernement', 'Les droits universels inherents a tout etre humain', 'Les droits des citoyens seulement', 'Les droits economiques uniquement'], rep: 1, expl: 'Reponse correcte : Les droits universels inherents a tout etre humain' },
      { q: 'Quand a eu lieu la Declaration universelle des droits de l\'homme ?', opts: ['1945', '1946', '1948', '1950'], rep: 2, expl: 'Reponse correcte : 1948' },
      { q: 'Qu\'est-ce que l\'etat de droit ?', opts: ['Le gouvernement par la force', 'La soumission de tous a la loi', 'La loi du plus fort', 'Le gouvernement religieux'], rep: 1, expl: 'Reponse correcte : La soumission de tous a la loi' },
      { q: 'Qu\'est-ce que la corruption ?', opts: ['L\'abus de pouvoir pour un gain personnel', 'La gestion transparente des fonds', 'Le respect des lois', 'La democratie participative'], rep: 0, expl: 'Reponse correcte : L\'abus de pouvoir pour un gain personnel' },
      { q: 'Qu\'est-ce que l\'UEMOA ?', opts: ['Union Economique et Monetaire Ouest-Africaine', 'Union des Etats du Maghreb et d\'Afrique', 'Union Educative et Medicale d\'Ouagadougou', 'Union Economique du Monde Occidental Africain'], rep: 0, expl: 'Reponse correcte : Union Economique et Monetaire Ouest-Africaine' },
      { q: 'Qu\'est-ce que la CEDEAO ?', opts: ['Communaute Economique Des Etats de l\'Afrique de l\'Ouest', 'Commission Economique pour le Developpement de l\'Afrique de l\'Ouest', 'Communaute des Etats pour le Developpement en Afrique', 'Cooperation Economique Des Etats Africains de l\'Ouest'], rep: 0, expl: 'Reponse correcte : Communaute Economique Des Etats de l\'Afrique de l\'Ouest' },
      { q: 'Qu\'est-ce que l\'OTAN ?', opts: ['Organisation pour le commerce', 'Alliance militaire atlantique', 'Organisation des Nations Unies', 'Union Africaine'], rep: 1, expl: 'Reponse correcte : Alliance militaire atlantique' },
      { q: 'Qu\'est-ce qu\'une ONG ?', opts: ['Organisation Non Gouvernementale', 'Organisation Nationale de Gestion', 'Office des Nations et Gouvernements', 'Organisation Nouvelle de Gestion'], rep: 0, expl: 'Reponse correcte : Organisation Non Gouvernementale' },
      { q: 'Qu\'est-ce que la Banque mondiale ?', opts: ['La banque des Nations Unies', 'Une institution financant le developpement des pays pauvres', 'La banque centrale americaine', 'Une banque privee internationale'], rep: 1, expl: 'Reponse correcte : Une institution financant le developpement des pays pauvres' },
      { q: 'Qu\'est-ce que le FMI ?', opts: ['Fonds Monetaire International', 'Fonds de Modernisation Industrielle', 'Fonds Mondial Islamique', 'Fondation Medicale Internationale'], rep: 0, expl: 'Reponse correcte : Fonds Monetaire International' },
      { q: 'Qu\'est-ce que l\'inflation ?', opts: ['La baisse des prix', 'La hausse generale des prix', 'La devaluation de la monnaie', 'La croissance economique'], rep: 1, expl: 'Reponse correcte : La hausse generale des prix' },
      { q: 'Qu\'est-ce que le commerce equitable ?', opts: ['Le libre-echange', 'Un commerce garantissant des prix justes aux producteurs', 'L\'echange de services', 'Le commerce en ligne'], rep: 1, expl: 'Reponse correcte : Un commerce garantissant des prix justes aux producteurs' },
      { q: 'Qu\'est-ce que la microfinance ?', opts: ['Les grandes banques', 'Prets de petites sommes aux personnes pauvres', 'L\'economie numerique', 'La finance islamique'], rep: 1, expl: 'Reponse correcte : Prets de petites sommes aux personnes pauvres' },
      { q: 'Quel est le pays le plus peuple du monde ?', opts: ['Chine', 'Inde', 'Etats-Unis', 'Nigeria'], rep: 1, expl: 'Reponse correcte : Inde' },
      { q: 'Quel est le pays le plus grand du monde ?', opts: ['Canada', 'Etats-Unis', 'Chine', 'Russie'], rep: 3, expl: 'Reponse correcte : Russie' },
      { q: 'Qu\'est-ce que la laicite ?', opts: ['La religion d\'Etat', 'La separation de l\'Etat et des religions', 'L\'interdiction de la religion', 'La priorite a l\'islam'], rep: 1, expl: 'Reponse correcte : La separation de l\'Etat et des religions' },
    ]
  },
  culture_maths_langues: {
    titre: '➗ Quiz — Maths, Français & Anglais',
    questions: [
      { q: 'Quelle est l\'aire d\'un cercle de rayon 5 cm ?', opts: ['25 pi cm2', '10 pi cm2', '5 pi cm2', '50 pi cm2'], rep: 0, expl: 'Reponse correcte : 25 pi cm2' },
      { q: 'Les solutions de x2 - 5x + 6 = 0 sont :', opts: ['x=2 et x=3', 'x=1 et x=6', 'x=-2 et x=-3', 'x=2 et x=-3'], rep: 0, expl: 'Reponse correcte : x=2 et x=3' },
      { q: 'En developpant (a+b)2, on obtient :', opts: ['a2+b2', 'a2+ab+b2', 'a2+2ab+b2', '2a+2b'], rep: 2, expl: 'Reponse correcte : a2+2ab+b2' },
      { q: 'Quel est le theoreme reliant les cotes d\'un triangle rectangle ?', opts: ['Thales', 'Pythagore', 'Euclide', 'Newton'], rep: 1, expl: 'Reponse correcte : Pythagore' },
      { q: 'Combien font 25% de 200 ?', opts: ['25', '40', '50', '75'], rep: 2, expl: 'Reponse correcte : 50' },
      { q: 'Quel est le PGCD de 12 et 18 ?', opts: ['3', '4', '6', '9'], rep: 2, expl: 'Reponse correcte : 6' },
      { q: 'Quel est le pluriel de \'oeil\' ?', opts: ['Des oeils', 'Des oeillets', 'Des yeux', 'Des oeils'], rep: 2, expl: 'Reponse correcte : Des yeux' },
      { q: 'Qu\'est-ce qu\'un pleonasme ?', opts: ['Une figure de style', 'Une redondance inutile', 'Une comparaison', 'Une metaphore'], rep: 1, expl: 'Reponse correcte : Une redondance inutile' },
      { q: 'Quel est le mode du verbe dans \'Bien qu\'il soit malade\' ?', opts: ['Indicatif', 'Conditionnel', 'Subjonctif', 'Imperatif'], rep: 2, expl: 'Reponse correcte : Subjonctif' },
      { q: 'Qu\'est-ce qu\'une anaphore ?', opts: ['Repetition d\'un mot en debut de phrase', 'Figure de remplacement', 'Comparaison implicite', 'Question rhetorique'], rep: 0, expl: 'Reponse correcte : Repetition d\'un mot en debut de phrase' },
      { q: 'Dans \'Les livres que j\'ai achetes\', pourquoi -s a achetes ?', opts: ['Sujet pluriel', 'COD place avant avoir', 'Auxiliaire etre', 'Erreur'], rep: 1, expl: 'Reponse correcte : COD place avant avoir' },
      { q: 'What is the past tense of \'go\'?', opts: ['Goed', 'Gone', 'Went', 'Goes'], rep: 2, expl: 'Reponse correcte : Went' },
      { q: 'What is the superlative of \'good\'?', opts: ['Better', 'Best', 'Gooder', 'More good'], rep: 1, expl: 'Reponse correcte : Best' },
      { q: 'Complete: If I ___ you, I would study harder.', opts: ['am', 'was', 'were', 'be'], rep: 2, expl: 'Reponse correcte : were' },
      { q: 'What is the plural of \'child\'?', opts: ['Childs', 'Childes', 'Children', 'Childrens'], rep: 2, expl: 'Reponse correcte : Children' },
      { q: 'What is the passive voice of \'She wrote the letter\'?', opts: ['The letter was written by her', 'The letter is written', 'She has written', 'The letter wrote itself'], rep: 0, expl: 'Reponse correcte : The letter was written by her' },
      { q: 'What is the past participle of \'write\'?', opts: ['Wrote', 'Written', 'Writed', 'Writ'], rep: 1, expl: 'Reponse correcte : Written' },
      { q: 'What does \'nevertheless\' mean?', opts: ['Therefore', 'However', 'Moreover', 'Although'], rep: 1, expl: 'Reponse correcte : However' },
      { q: 'Which is correct: I wish I ___ fly.', opts: ['can', 'could', 'would', 'will'], rep: 1, expl: 'Reponse correcte : could' },
      { q: 'What is the comparative of \'far\'?', opts: ['Farer', 'More far', 'Further', 'Farthest'], rep: 2, expl: 'Reponse correcte : Further' },
      { q: 'Combien font 2 puissance 10 ?', opts: ['512', '1024', '2048', '256'], rep: 1, expl: 'Reponse correcte : 1024' },
      { q: 'Qu\'est-ce que la mediane d\'une serie statistique ?', opts: ['La valeur la plus frequente', 'La valeur centrale qui divise en deux parties egales', 'La moyenne', 'La valeur maximale'], rep: 1, expl: 'Reponse correcte : La valeur centrale qui divise en deux parties egales' },
      { q: 'Quel est le volume d\'un cube de cote 5 cm ?', opts: ['25 cm3', '100 cm3', '125 cm3', '150 cm3'], rep: 2, expl: 'Reponse correcte : 125 cm3' },
      { q: 'Qu\'est-ce qu\'une fonction affine ?', opts: ['f(x) = ax2', 'f(x) = ax + b', 'f(x) = a/x', 'f(x) = a^x'], rep: 1, expl: 'Reponse correcte : f(x) = ax + b' },
      { q: 'Le discriminant Delta = b2-4ac sert a determiner quoi ?', opts: ['La nature des solutions d\'une equation', 'Le perimetre d\'un cercle', 'La derivee d\'une fonction', 'La valeur de pi'], rep: 0, expl: 'Reponse correcte : La nature des solutions d\'une equation' },
    ]
  },
  culture_divers: {
    titre: '💡 Quiz — Informatique & Divers',
    questions: [
      { q: 'Que signifie HTTP ?', opts: ['HyperText Transfer Protocol', 'High Tech Text Program', 'Hyper Transfer Text Process', 'HyperText Technical Protocol'], rep: 0, expl: 'Reponse correcte : HyperText Transfer Protocol' },
      { q: 'Qui a cree Linux ?', opts: ['Bill Gates', 'Steve Jobs', 'Linus Torvalds', 'Mark Zuckerberg'], rep: 2, expl: 'Reponse correcte : Linus Torvalds' },
      { q: 'Qu\'est-ce qu\'un algorithme ?', opts: ['Un langage de programmation', 'Une suite d\'instructions pour resoudre un probleme', 'Un type de virus', 'Un systeme d\'exploitation'], rep: 1, expl: 'Reponse correcte : Une suite d\'instructions pour resoudre un probleme' },
      { q: 'Qu\'est-ce que l\'intelligence artificielle ?', opts: ['La programmation classique', 'La simulation de l\'intelligence humaine par les machines', 'Un type de robot', 'Un systeme de securite'], rep: 1, expl: 'Reponse correcte : La simulation de l\'intelligence humaine par les machines' },
      { q: 'Qui a invente le World Wide Web ?', opts: ['Al Gore', 'Tim Berners-Lee', 'Steve Jobs', 'Bill Gates'], rep: 1, expl: 'Reponse correcte : Tim Berners-Lee' },
      { q: 'Qu\'est-ce que la biodiversite ?', opts: ['La variete des genes seulement', 'La variete des especes et des ecosystemes', 'La diversite culturelle', 'La diversite geographique'], rep: 1, expl: 'Reponse correcte : La variete des especes et des ecosystemes' },
      { q: 'Qu\'est-ce que l\'effet de serre ?', opts: ['La culture sous serre', 'Le rechauffement de la Terre par les gaz atmospheriques', 'Un phenomene spatial', 'La couche d\'ozone'], rep: 1, expl: 'Reponse correcte : Le rechauffement de la Terre par les gaz atmospheriques' },
      { q: 'Qu\'est-ce que la desertification ?', opts: ['La creation de deserts artificiels', 'La degradation des terres en zones arides', 'L\'irrigation des deserts', 'La reforestation'], rep: 1, expl: 'Reponse correcte : La degradation des terres en zones arides' },
      { q: 'Qu\'est-ce que l\'agriculture biologique ?', opts: ['L\'agriculture intensive', 'L\'agriculture sans pesticides chimiques', 'L\'agriculture OGM', 'L\'agriculture mecanisee'], rep: 1, expl: 'Reponse correcte : L\'agriculture sans pesticides chimiques' },
      { q: 'Qu\'est-ce qu\'une espece menacee d\'extinction ?', opts: ['Une espece invasive', 'Une espece dont la population diminue dangereusement', 'Une espece nouvelle', 'Une espece domestiquee'], rep: 1, expl: 'Reponse correcte : Une espece dont la population diminue dangereusement' },
      { q: 'Qui a construit les pyramides de Gizeh ?', opts: ['Les Romains', 'Les Grecs', 'Les anciens Egyptiens', 'Les Arabes'], rep: 2, expl: 'Reponse correcte : Les anciens Egyptiens' },
      { q: 'Quel est le symbole olympique ?', opts: ['3 anneaux', '4 anneaux', '5 anneaux', '6 anneaux'], rep: 2, expl: 'Reponse correcte : 5 anneaux' },
      { q: 'Qui a marche sur la Lune en premier ?', opts: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn'], rep: 1, expl: 'Reponse correcte : Neil Armstrong' },
      { q: 'Quel est le plus grand animal du monde ?', opts: ['L\'elephant d\'Afrique', 'Le requin baleine', 'La baleine bleue', 'Le crocodile marin'], rep: 2, expl: 'Reponse correcte : La baleine bleue' },
      { q: 'Qu\'est-ce que la Francophonie ?', opts: ['L\'Organisation internationale de la langue francaise', 'Un parti politique', 'Un style litteraire', 'Une radio internationale'], rep: 0, expl: 'Reponse correcte : L\'Organisation internationale de la langue francaise' },
      { q: 'Qui a fonde la Croix-Rouge ?', opts: ['Henri Dunant', 'Albert Schweitzer', 'Florence Nightingale', 'Louis Pasteur'], rep: 0, expl: 'Reponse correcte : Henri Dunant' },
      { q: 'Quel est le plus vieux monument du monde connu ?', opts: ['Les pyramides de Gizeh', 'Stonehenge', 'Le Colisee', 'Gobekli Tepe'], rep: 3, expl: 'Reponse correcte : Gobekli Tepe' },
      { q: 'Qui a invente l\'imprimerie en Europe ?', opts: ['Leonard de Vinci', 'Gutenberg', 'Copernic', 'Bacon'], rep: 1, expl: 'Reponse correcte : Gutenberg' },
      { q: 'Qu\'est-ce que la Renaissance ?', opts: ['La reforme religieuse', 'Le renouveau artistique et intellectuel en Europe', 'La revolution industrielle', 'La colonisation'], rep: 1, expl: 'Reponse correcte : Le renouveau artistique et intellectuel en Europe' },
      { q: 'Qu\'est-ce que la culture comme facteur de developpement ?', opts: ['Un luxe pour pays riches', 'Un levier essentiel pour le developpement humain et economique', 'Un frein au developpement', 'Un secteur secondaire'], rep: 1, expl: 'Reponse correcte : Un levier essentiel pour le developpement humain et economique' },
    ]
  },};
